-- ScentMatch: kuratierte Charge 6 – viele neue Marken + bekannte Bestseller.
-- Faktenbasiert kuratiert (keine gescrapten Fragmente). Im Supabase SQL Editor ausfuehren.
-- Wiederholbar: brands -> on conflict (name) do nothing, perfumes -> on conflict (slug) do nothing.
-- Bereits vorhandene Marken/Duefte werden automatisch uebersprungen.

-- ============ 1) Marken (neue + bestehende; bestehende werden ignoriert) ============
insert into public.brands (name, slug, country) values
  ('Laura Biagiotti',     'laura-biagiotti',     'Italien'),
  ('Gisada',              'gisada',              'Schweiz'),
  ('Victoria''s Secret',  'victorias-secret',    'USA'),
  ('Emporio Armani',      'emporio-armani',      'Italien'),
  ('Lacoste',             'lacoste',             'Frankreich'),
  ('Lanvin',              'lanvin',              'Frankreich'),
  ('Jil Sander',          'jil-sander',          'Deutschland'),
  ('Abercrombie & Fitch', 'abercrombie-fitch',   'USA'),
  ('Joop!',               'joop',                'Deutschland'),
  ('Calvin Klein',        'calvin-klein',        'USA'),
  ('Kenzo',               'kenzo',               'Frankreich'),
  ('Billie Eilish',       'billie-eilish',       'USA'),
  ('Nina Ricci',          'nina-ricci',          'Frankreich'),
  ('Elizabeth Arden',     'elizabeth-arden',     'USA'),
  ('Loewe',               'loewe',               'Spanien'),
  ('Guess',               'guess',               'USA'),
  ('Lolita Lempicka',     'lolita-lempicka',     'Frankreich'),
  ('Michael Kors',        'michael-kors',        'USA'),
  ('Britney Spears',      'britney-spears',      'USA'),
  ('Swiss Arabian',       'swiss-arabian',       'VAE'),
  ('DKNY',                'dkny',                'USA'),
  ('Sol de Janeiro',      'sol-de-janeiro',      'USA'),
  ('Roberto Cavalli',     'roberto-cavalli',     'Italien'),
  ('Zadig & Voltaire',    'zadig-voltaire',      'Frankreich'),
  ('Moschino',            'moschino',            'Italien'),
  ('Cacharel',            'cacharel',            'Frankreich'),
  ('Tommy Hilfiger',      'tommy-hilfiger',      'USA'),
  ('Dsquared2',           'dsquared2',           'Italien'),
  ('Jimmy Choo',          'jimmy-choo',          'UK'),
  ('Bruno Banani',        'bruno-banani',        'Deutschland'),
  ('Elie Saab',           'elie-saab',           'Libanon'),
  ('Diesel',              'diesel',              'Italien'),
  ('Cartier',             'cartier',             'Frankreich'),
  ('Escentric Molecules', 'escentric-molecules', 'Deutschland'),
  ('Penhaligon''s',       'penhaligons',         'UK'),
  ('Tiziana Terenzi',     'tiziana-terenzi',     'Italien')
on conflict (name) do nothing;

-- ============ 2) Duefte (inkl. Noten) ============
insert into public.perfumes
  (brand_id, perfume_name, slug, gender, fragrance_family, price_chf, longevity, sillage, scentmatch_score, season, occasion, top_notes, heart_notes, base_notes)
values
  ((select id from public.brands where name='Laura Biagiotti'),     'Roma',                 'lb-roma',                'Women',  'floral',   45,  6, 6, 82, 'Ganzjährig',    'Alltag', ARRAY['Bergamotte','Schwarze Johannisbeere','Hyazinthe'], ARRAY['Rose','Jasmin','Nelke'], ARRAY['Moschus','Vanille','Sandelholz']),
  ((select id from public.brands where name='Gisada'),              'Ambassador',           'gisada-ambassador',      'Men',    'woody',    75,  8, 7, 86, 'Herbst/Winter', 'Abend',  ARRAY['Bergamotte','Apfel','Pfeffer'], ARRAY['Zimt','Rose','Geranie'], ARRAY['Sandelholz','Amber','Moschus']),
  ((select id from public.brands where name='Gisada'),              'Ambassadora',          'gisada-ambassadora',     'Women',  'floral',   75,  7, 6, 84, 'Ganzjährig',    'Date',   ARRAY['Himbeere','Bergamotte'], ARRAY['Jasmin','Orangenblüte'], ARRAY['Vanille','Moschus','Sandelholz']),
  ((select id from public.brands where name='Victoria''s Secret'),  'Bombshell',            'vs-bombshell',           'Women',  'floral',   60,  7, 7, 84, 'Frühling',      'Date',   ARRAY['Purpurorchidee','Grapefruit'], ARRAY['Pfingstrose','Erdbeere'], ARRAY['Moschus','Zedernholz']),
  ((select id from public.brands where name='Lancome'),             'Idôle',                'lancome-idole',          'Women',  'floral',   95,  7, 6, 86, 'Ganzjährig',    'Alltag', ARRAY['Bergamotte','Birne','Rosa Pfeffer'], ARRAY['Rose','Jasmin'], ARRAY['Weißer Moschus','Vanille','Zedernholz']),
  ((select id from public.brands where name='Lancome'),             'La Nuit Trésor',       'lancome-la-nuit-tresor', 'Women',  'gourmand', 110, 8, 7, 87, 'Herbst/Winter', 'Abend',  ARRAY['Litschi','Bergamotte'], ARRAY['Rose','Vanilleorchidee'], ARRAY['Tonkabohne','Vanille','Patchouli']),
  ((select id from public.brands where name='Emporio Armani'),      'Stronger With You',    'ea-stronger-with-you',   'Men',    'gourmand', 75,  8, 7, 88, 'Herbst/Winter', 'Date',   ARRAY['Kardamom','Rosa Pfeffer','Minze'], ARRAY['Lavendel','Salbei','Veilchen'], ARRAY['Vanille','Kastanie','Amber']),
  ((select id from public.brands where name='Emporio Armani'),      'Because It''s You',    'ea-because-its-you',     'Women',  'floral',   75,  7, 6, 83, 'Ganzjährig',    'Date',   ARRAY['Himbeere','Birne'], ARRAY['Rose','Jasmin'], ARRAY['Vanille','Patchouli','Moschus']),
  ((select id from public.brands where name='Paco Rabanne'),        '1 Million',            'pr-1-million',           'Men',    'woody',    80,  8, 8, 88, 'Herbst/Winter', 'Abend',  ARRAY['Grapefruit','Minze','Blutorange'], ARRAY['Zimt','Rose','Gewürze'], ARRAY['Leder','Amber','Patchouli']),
  ((select id from public.brands where name='Paco Rabanne'),        'Lady Million',         'pr-lady-million',        'Women',  'floral',   80,  7, 7, 86, 'Ganzjährig',    'Date',   ARRAY['Neroli','Bitterorange'], ARRAY['Orangenblüte','Jasmin','Himbeere'], ARRAY['Honig','Patchouli','Amber']),
  ((select id from public.brands where name='Paco Rabanne'),        'Invictus',             'pr-invictus',            'Men',    'clean',    75,  7, 7, 85, 'Sommer',        'Alltag', ARRAY['Grapefruit','Meeresnote'], ARRAY['Lorbeer','Jasmin'], ARRAY['Eichenmoos','Amber','Guajakholz']),
  ((select id from public.brands where name='Lacoste'),             'L.12.12 Blanc',        'lacoste-blanc',          'Men',    'clean',    55,  6, 6, 83, 'Sommer',        'Alltag', ARRAY['Grapefruit','Rosmarin','Kardamom'], ARRAY['Tuberose','Zedernholz'], ARRAY['Leder','Moschus','Vetiver']),
  ((select id from public.brands where name='Bvlgari'),             'Man in Black',         'bvlgari-man-in-black',   'Men',    'gourmand', 90,  8, 8, 86, 'Herbst/Winter', 'Abend',  ARRAY['Rum','Gewürze'], ARRAY['Tuberose','Leder','Iris'], ARRAY['Tonkabohne','Amber','Benzoe']),
  ((select id from public.brands where name='Bvlgari'),             'Omnia Crystalline',    'bvlgari-omnia-crystalline','Women','clean',    70,  6, 5, 82, 'Sommer',        'Alltag', ARRAY['Bambus','Litschi'], ARRAY['Lotus','Teenote'], ARRAY['Balsaholz','Moschus']),
  ((select id from public.brands where name='Lanvin'),              'Éclat d''Arpège',      'lanvin-eclat-darpege',   'Women',  'floral',   55,  6, 6, 84, 'Frühling',      'Alltag', ARRAY['Grüner Flieder','Zitrone'], ARRAY['Flieder','Pfingstrose','Glyzinie'], ARRAY['Zedernholz','Moschus','Pfirsich']),
  ((select id from public.brands where name='Jil Sander'),          'Sun',                  'jil-sander-sun',         'Women',  'clean',    45,  5, 5, 80, 'Sommer',        'Alltag', ARRAY['Anjou-Birne','Fruchtnoten'], ARRAY['weiße Blüten','Pfeffer'], ARRAY['Moschus','Holz']),
  ((select id from public.brands where name='Abercrombie & Fitch'), 'Fierce',               'af-fierce',              'Men',    'woody',    75,  7, 7, 84, 'Ganzjährig',    'Alltag', ARRAY['Petitgrain','Kardamom','Zitrone'], ARRAY['Jasmin','Salbei'], ARRAY['Vetiver','Moschus','Holz']),
  ((select id from public.brands where name='Joop!'),               'Homme',                'joop-homme',             'Men',    'gourmand', 45,  8, 8, 82, 'Herbst/Winter', 'Abend',  ARRAY['Mandarine','Bergamotte','Honig'], ARRAY['Zimt','Orangenblüte','Jasmin'], ARRAY['Vanille','Tabak','Tonkabohne']),
  ((select id from public.brands where name='Calvin Klein'),        'Euphoria',             'ck-euphoria',            'Women',  'woody',    65,  7, 7, 85, 'Herbst/Winter', 'Date',   ARRAY['Granatapfel','Persimone'], ARRAY['Lotus','Orchidee'], ARRAY['Amber','Mahagoni','Moschus']),
  ((select id from public.brands where name='Calvin Klein'),        'CK Be',                'ck-be',                  'Unisex', 'clean',    40,  5, 5, 80, 'Sommer',        'Alltag', ARRAY['Bergamotte','Mandarine','Wacholder'], ARRAY['Magnolie','Pfirsich'], ARRAY['Moschus','Sandelholz','Vanille']),
  ((select id from public.brands where name='Kenzo'),               'Flower by Kenzo',      'kenzo-flower',           'Women',  'floral',   70,  7, 6, 84, 'Ganzjährig',    'Alltag', ARRAY['Schwarze Johannisbeere','Mandarine'], ARRAY['Rose','Veilchen','Hagebutte'], ARRAY['Vanille','Moschus','weißer Moschus']),
  ((select id from public.brands where name='Billie Eilish'),       'Eilish',               'billie-eilish-eilish',   'Women',  'gourmand', 60,  7, 6, 83, 'Herbst/Winter', 'Date',   ARRAY['Mandarine','Beeren'], ARRAY['Vanille','Kakao','Gewürze'], ARRAY['Tonkabohne','Moschus','Sandelholz']),
  ((select id from public.brands where name='Nina Ricci'),          'Nina',                 'nina-ricci-nina',        'Women',  'floral',   55,  6, 6, 83, 'Frühling',      'Date',   ARRAY['Zitrone','Limette'], ARRAY['Apfel','Pfingstrose','Praline'], ARRAY['Apfelblüte','Zedernholz','Moschus']),
  ((select id from public.brands where name='Elizabeth Arden'),     'Green Tea',            'ea-green-tea',           'Women',  'clean',    35,  5, 5, 80, 'Sommer',        'Alltag', ARRAY['Bergamotte','Zitrone','Rhabarber'], ARRAY['Grüner Tee','Jasmin','Minze'], ARRAY['Moschus','Eichenmoos','Karamell']),
  ((select id from public.brands where name='Loewe'),               'Solo Loewe',           'loewe-solo',             'Men',    'woody',    80,  7, 7, 83, 'Ganzjährig',    'Alltag', ARRAY['Bergamotte','Zypresse'], ARRAY['Kardamom','Pfeffer'], ARRAY['Zedernholz','Tonkabohne','Moschus']),
  ((select id from public.brands where name='Montale'),             'Intense Café',         'montale-intense-cafe',   'Unisex', 'gourmand', 110, 9, 8, 88, 'Herbst/Winter', 'Abend',  ARRAY['Kaffee','Rose'], ARRAY['Rose','weiße Blüten'], ARRAY['Vanille','Amber','Moschus']),
  ((select id from public.brands where name='Guess'),               'Seductive',            'guess-seductive',        'Women',  'floral',   35,  6, 6, 79, 'Ganzjährig',    'Date',   ARRAY['Schwarze Johannisbeere','Apfel'], ARRAY['Lilie','Jasmin'], ARRAY['Amber','Sandelholz','Moschus']),
  ((select id from public.brands where name='Lolita Lempicka'),     'Lolita Lempicka',      'lolita-lempicka-edp',    'Women',  'gourmand', 60,  8, 7, 84, 'Herbst/Winter', 'Abend',  ARRAY['Anis','Efeu'], ARRAY['Lakritz','Veilchen','Iris'], ARRAY['Tonkabohne','Vanille','Vetiver']),
  ((select id from public.brands where name='Michael Kors'),        'Wonderlust',           'mk-wonderlust',          'Women',  'floral',   75,  7, 6, 83, 'Frühling',      'Date',   ARRAY['Bergamotte','Rosa Pfeffer'], ARRAY['Mandelmilch','Jasmin'], ARRAY['Benzoe','Vanille','Moschus']),
  ((select id from public.brands where name='Ariana Grande'),       'Cloud',                'ariana-cloud',           'Women',  'gourmand', 55,  7, 7, 86, 'Ganzjährig',    'Date',   ARRAY['Lavendel','Birne','Bergamotte'], ARRAY['Kokosnuss','Praline'], ARRAY['Moschus','Holz','Vanille']),
  ((select id from public.brands where name='Britney Spears'),      'Fantasy',              'britney-fantasy',        'Women',  'gourmand', 35,  6, 6, 80, 'Herbst/Winter', 'Date',   ARRAY['Litschi','Quitte','Kiwi'], ARRAY['Cupcake','Jasmin','Orchidee'], ARRAY['Moschus','Amber','Holz']),
  ((select id from public.brands where name='Swiss Arabian'),       'Shaghaf Oud',          'sa-shaghaf-oud',         'Unisex', 'gourmand', 50,  9, 8, 85, 'Herbst/Winter', 'Abend',  ARRAY['Safran','Rose'], ARRAY['Oud','Beeren'], ARRAY['Vanille','Amber','Moschus']),
  ((select id from public.brands where name='DKNY'),                'Be Delicious',         'dkny-be-delicious',      'Women',  'clean',    55,  6, 6, 83, 'Frühling',      'Alltag', ARRAY['Grüner Apfel','Grapefruit','Gurke'], ARRAY['Maiglöckchen','Rose'], ARRAY['Sandelholz','Amber','Moschus']),
  ((select id from public.brands where name='Sol de Janeiro'),      'Cheirosa 62',          'sdj-cheirosa-62',        'Women',  'gourmand', 40,  7, 7, 84, 'Sommer',        'Alltag', ARRAY['Salzkaramell','Pistazie'], ARRAY['Vanille'], ARRAY['Amber','Sandelholz']),
  ((select id from public.brands where name='Roberto Cavalli'),     'Just Cavalli Her',     'cavalli-just-her',       'Women',  'floral',   45,  6, 6, 80, 'Sommer',        'Date',   ARRAY['Bergamotte','Cassis'], ARRAY['Orangenblüte','Jasmin'], ARRAY['Moschus','Zedernholz']),
  ((select id from public.brands where name='Zadig & Voltaire'),    'This is Her!',         'zv-this-is-her',         'Women',  'gourmand', 70,  7, 7, 85, 'Herbst/Winter', 'Date',   ARRAY['Pink Pfeffer'], ARRAY['Jasmin Sambac','Kastanie'], ARRAY['Vanille','Sandelholz','Zedernholz']),
  ((select id from public.brands where name='Zadig & Voltaire'),    'This is Him!',         'zv-this-is-him',         'Men',    'gourmand', 70,  7, 7, 84, 'Herbst/Winter', 'Abend',  ARRAY['Bergamotte','Pink Pfeffer'], ARRAY['Tonkabohne','Schwarze Vanille'], ARRAY['Holz','Moschus','Kaffee']),
  ((select id from public.brands where name='Moschino'),            'Toy Boy',              'moschino-toy-boy',       'Men',    'woody',    75,  7, 7, 84, 'Herbst/Winter', 'Abend',  ARRAY['Birne','Pfeffer'], ARRAY['Rose','Geranie','Magnolie'], ARRAY['Zedernholz','Sandelholz','Patchouli']),
  ((select id from public.brands where name='Cacharel'),            'Amor Amor',            'cacharel-amor-amor',     'Women',  'floral',   50,  6, 6, 81, 'Frühling',      'Date',   ARRAY['Bergamotte','Johannisbeere','Mandarine'], ARRAY['Jasmin','Lilie','Rose'], ARRAY['Vanille','Moschus','Amber']),
  ((select id from public.brands where name='Acqua di Parma'),      'Colonia',              'adp-colonia',            'Unisex', 'clean',    130, 6, 6, 87, 'Sommer',        'Büro',   ARRAY['Zitrone','Bergamotte','Orange'], ARRAY['Lavendel','Rosmarin','Rose'], ARRAY['Vetiver','Patchouli','Sandelholz']),
  ((select id from public.brands where name='Tommy Hilfiger'),      'Tommy Girl',           'th-tommy-girl',          'Women',  'clean',    45,  5, 5, 80, 'Sommer',        'Alltag', ARRAY['Apfelblüte','Kamelie','Zitrone'], ARRAY['Tee','Mimose'], ARRAY['weiße Zeder','Sandelholz']),
  ((select id from public.brands where name='Dsquared2'),           'Wood for Him',         'dsquared2-wood',         'Men',    'woody',    60,  6, 6, 81, 'Frühling',      'Alltag', ARRAY['Mandarine','Bergamotte','Veilchenblatt'], ARRAY['Muskatnuss','Pflaume'], ARRAY['Amber','Zedernholz','Moschus']),
  ((select id from public.brands where name='Jimmy Choo'),          'Jimmy Choo',           'jimmy-choo-edp',         'Women',  'floral',   65,  6, 6, 82, 'Ganzjährig',    'Date',   ARRAY['Birne','grüne Note'], ARRAY['Tigerorchidee'], ARRAY['Toffee','Patchouli']),
  ((select id from public.brands where name='Bruno Banani'),        'Man''s Best',          'bb-mans-best',           'Men',    'clean',    30,  6, 6, 79, 'Sommer',        'Alltag', ARRAY['Bergamotte','Apfel'], ARRAY['Geranie','Lavendel'], ARRAY['Vetiver','Moschus','Holz']),
  ((select id from public.brands where name='Elie Saab'),           'Le Parfum',            'elie-saab-le-parfum',    'Women',  'floral',   95,  7, 7, 86, 'Frühling',      'Date',   ARRAY['Orangenblüte'], ARRAY['Jasmin'], ARRAY['Patchouli','Zedernholz','Honig']),
  ((select id from public.brands where name='Diesel'),              'Only the Brave',       'diesel-only-the-brave',  'Men',    'woody',    55,  6, 6, 81, 'Ganzjährig',    'Alltag', ARRAY['Zitrone','Mandarine','Veilchenblatt'], ARRAY['Koriander','Tabak'], ARRAY['Amber','Leder','Zedernholz']),
  ((select id from public.brands where name='Cartier'),             'Declaration',          'cartier-declaration',    'Men',    'woody',    90,  7, 7, 84, 'Frühling',      'Büro',   ARRAY['Bitterorange','Bergamotte','Mandarine'], ARRAY['Kümmel','Birkenholz','Pfeffer'], ARRAY['Zedernholz','Vetiver','Amber']),
  ((select id from public.brands where name='Cartier'),             'La Panthère',          'cartier-la-panthere',    'Women',  'floral',   100, 7, 6, 84, 'Ganzjährig',    'Date',   ARRAY['Gardenie'], ARRAY['Gardenie','Tuberose'], ARRAY['Moschus','Holz']),
  ((select id from public.brands where name='Escentric Molecules'), 'Molecule 01',          'em-molecule-01',         'Unisex', 'woody',    90,  7, 6, 85, 'Ganzjährig',    'Alltag', ARRAY['Iso E Super'], ARRAY['Iso E Super'], ARRAY['Zedernholz','samtiges Holz']),
  ((select id from public.brands where name='Penhaligon''s'),       'Halfeti',              'penhaligons-halfeti',    'Unisex', 'woody',    200, 9, 8, 88, 'Herbst/Winter', 'Abend',  ARRAY['Bergamotte','Grapefruit','Artemisia'], ARRAY['Rose','Jasmin','Zimt','Safran'], ARRAY['Oud','Leder','Sandelholz','Tonkabohne']),
  ((select id from public.brands where name='Tiziana Terenzi'),     'Kirke',                'tt-kirke',               'Women',  'gourmand', 180, 9, 9, 87, 'Ganzjährig',    'Date',   ARRAY['Passionsfrucht','Pfirsich','Litschi'], ARRAY['Maiglöckchen','Cassis'], ARRAY['Vanille','Moschus','Sandelholz']),
  ((select id from public.brands where name='Givenchy'),            'L''Interdit',          'givenchy-linterdit',     'Women',  'floral',   90,  7, 7, 86, 'Ganzjährig',    'Date',   ARRAY['Birne','Bergamotte'], ARRAY['Tuberose','Orangenblüte','Jasmin'], ARRAY['Vetiver','Patchouli','Ambroxan']),
  ((select id from public.brands where name='Givenchy'),            'Gentleman Société',    'givenchy-gentleman-societe','Men', 'woody',    95,  8, 7, 85, 'Herbst/Winter', 'Abend',  ARRAY['Sternanis'], ARRAY['Iris','Pfeffer'], ARRAY['Patchouli','Vetiver','Holz']),
  ((select id from public.brands where name='Guerlain'),            'Mon Guerlain',         'guerlain-mon',           'Women',  'gourmand', 95,  7, 7, 86, 'Ganzjährig',    'Date',   ARRAY['Bergamotte','Lavendel'], ARRAY['Jasmin Sambac'], ARRAY['Vanille','Tonkabohne','Sandelholz']),
  ((select id from public.brands where name='Mugler'),              'Alien',                'mugler-alien',           'Women',  'floral',   90,  9, 8, 87, 'Herbst/Winter', 'Abend',  ARRAY['Mandarine'], ARRAY['Jasmin Sambac'], ARRAY['Cashmeran','weißer Amber']),
  ((select id from public.brands where name='Azzaro'),              'The Most Wanted',      'azzaro-the-most-wanted', 'Men',    'gourmand', 80,  8, 8, 86, 'Herbst/Winter', 'Date',   ARRAY['Ingwer','Kardamom'], ARRAY['Toffee','Lavendel'], ARRAY['Vanille','Amberholz']),
  ((select id from public.brands where name='Versace'),             'Eros Flame',           'versace-eros-flame',     'Men',    'woody',    80,  8, 8, 85, 'Herbst/Winter', 'Abend',  ARRAY['Mandarine','Schwarzer Pfeffer','Rosmarin'], ARRAY['Pfeffer','Geranie','Rose'], ARRAY['Vanille','Tonkabohne','Sandelholz','Patchouli']),
  ((select id from public.brands where name='Dior'),                'Sauvage Elixir',       'dior-sauvage-elixir',    'Men',    'woody',    130, 9, 9, 90, 'Herbst/Winter', 'Abend',  ARRAY['Zimt','Muskatnuss','Kardamom','Grapefruit'], ARRAY['Lavendel'], ARRAY['Lakritz','Sandelholz','Amber','Patchouli']),
  ((select id from public.brands where name='Chanel'),              'Chance Eau Tendre',    'chanel-chance-eau-tendre','Women', 'floral',   130, 6, 6, 86, 'Frühling',      'Date',   ARRAY['Grapefruit','Quitte'], ARRAY['Jasmin','Hyazinthe'], ARRAY['weißer Moschus','Amber']),
  ((select id from public.brands where name='Lattafa'),             'Asad',                 'lattafa-asad',           'Men',    'gourmand', 35,  9, 8, 85, 'Herbst/Winter', 'Abend',  ARRAY['Pfeffer','Ananas','Bergamotte'], ARRAY['Lavendel','Veilchen'], ARRAY['Vanille','Ambroxan','Moschus']),
  ((select id from public.brands where name='Lattafa'),             'Yara',                 'lattafa-yara',           'Women',  'gourmand', 30,  8, 8, 84, 'Ganzjährig',    'Date',   ARRAY['Orchidee','Heliotrop'], ARRAY['tropische Früchte'], ARRAY['Vanille','Tonkabohne','Sandelholz'])
on conflict (slug) do nothing;
