-- ScentMatch: Charge 9 – fehlende Gegenstücke (Damen-/Herren-Version bekannter Linien).
-- Faktenbasiert. Im Supabase SQL Editor ausfuehren. Wiederholbar (on conflict (slug) do nothing).
-- Alle Marken existieren bereits aus früheren Chargen.

insert into public.perfumes
  (brand_id, perfume_name, slug, gender, fragrance_family, price_chf, longevity, sillage, scentmatch_score, season, occasion, top_notes, heart_notes, base_notes)
values
  ((select id from public.brands where name='Cerruti'),           '1881 pour Femme',      'cerruti-1881-femme',     'Women', 'floral',  45, 6, 6, 80, 'Ganzjährig',    'Date',   ARRAY['Mimose','Veilchenblatt','Mandarine'], ARRAY['Jasmin','Rose','Maiglöckchen'], ARRAY['Sandelholz','Moschus','Amber']),
  ((select id from public.brands where name='Versace'),           'Eros Pour Femme',      'versace-eros-femme',     'Women', 'floral',  80, 7, 7, 85, 'Ganzjährig',    'Date',   ARRAY['Sizilianische Zitrone','Granatapfel'], ARRAY['Pfingstrose','Jasmin Sambac'], ARRAY['Sandelholz','Moschus','Amber']),
  ((select id from public.brands where name='Davidoff'),          'Cool Water Woman',     'davidoff-cool-water-woman','Women','clean',  40, 6, 6, 81, 'Sommer',        'Alltag', ARRAY['Wassermelone','Ananas','Schwarze Johannisbeere'], ARRAY['Lotus','Maiglöckchen'], ARRAY['Moschus','Sandelholz']),
  ((select id from public.brands where name='DKNY'),              'Be Delicious Men',     'dkny-be-delicious-men',  'Men',   'clean',   55, 6, 6, 80, 'Sommer',        'Alltag', ARRAY['Grapefruit','Gurke'], ARRAY['Salbei','Lavendel'], ARRAY['Amber','Moschus','Holznoten']),
  ((select id from public.brands where name='Calvin Klein'),      'Eternity for Men',     'ck-eternity-men',        'Men',   'clean',   60, 6, 6, 83, 'Frühling',      'Büro',   ARRAY['Lavendel','Mandarine','Bergamotte'], ARRAY['Salbei','Geranie','Muskatnuss'], ARRAY['Sandelholz','Moschus','Amber']),
  ((select id from public.brands where name='Jimmy Choo'),        'Jimmy Choo Man',       'jimmy-choo-man',         'Men',   'woody',   65, 7, 7, 83, 'Ganzjährig',    'Date',   ARRAY['Honigmelone','Lavendel'], ARRAY['Ananas','Geranie'], ARRAY['Patchouli','Amberholz']),
  ((select id from public.brands where name='Hugo Boss'),         'Boss Alive',           'boss-alive',             'Women', 'gourmand',75, 6, 6, 82, 'Ganzjährig',    'Date',   ARRAY['Apfel','Bergamotte','Pflaume'], ARRAY['Jasmin'], ARRAY['Vanille','Sandelholz','Kaschmirholz']),
  ((select id from public.brands where name='Joop!'),             'Le Bain',              'joop-le-bain',           'Women', 'gourmand',45, 6, 6, 80, 'Ganzjährig',    'Date',   ARRAY['Cassis','Litschi'], ARRAY['Orangenblüte'], ARRAY['Vanille','Moschus','Sandelholz']),
  ((select id from public.brands where name='Bruno Banani'),      'Woman',                'bb-woman',               'Women', 'floral',  30, 5, 5, 78, 'Frühling',      'Alltag', ARRAY['Cassis','Pflaume'], ARRAY['Magnolie','Freesie'], ARRAY['Sandelholz','Moschus','Vanille']),
  ((select id from public.brands where name='Mexx'),              'Man',                  'mexx-man',               'Men',   'clean',   30, 5, 5, 78, 'Sommer',        'Alltag', ARRAY['Mandarine','Wassermelone'], ARRAY['Muskatellersalbei','Pfeffer'], ARRAY['Sandelholz','Moschus']),
  ((select id from public.brands where name='Dolce & Gabbana'),   'Light Blue pour Homme','dg-light-blue-homme',    'Men',   'clean',   80, 6, 6, 84, 'Sommer',        'Alltag', ARRAY['Grapefruit','Mandarine','Wacholder'], ARRAY['Pfeffer','Rosmarin'], ARRAY['Moschus','Weihrauch','Eichenmoos']),
  ((select id from public.brands where name='Lacoste'),           'Pour Femme',           'lacoste-pour-femme',     'Women', 'floral',  55, 6, 6, 80, 'Ganzjährig',    'Date',   ARRAY['Pflaume','Pink Pfeffer'], ARRAY['Jasmin','Rose'], ARRAY['Sandelholz','Vanille','Moschus']),
  ((select id from public.brands where name='Burberry'),          'Brit for Men',         'burberry-brit-men',      'Men',   'woody',   60, 6, 6, 80, 'Herbst/Winter', 'Date',   ARRAY['Mandarine','Grüne Note','Kardamom'], ARRAY['Muskatnuss','Zedernholz'], ARRAY['Tonkabohne','Vetiver','Amber']),
  ((select id from public.brands where name='Mugler'),            'A*Men',                'mugler-amen',            'Men',   'gourmand',70, 8, 8, 84, 'Herbst/Winter', 'Abend',  ARRAY['Lavendel','Bergamotte','Minze'], ARRAY['Kaffee','Karamell'], ARRAY['Patchouli','Tonkabohne','Vanille']),
  ((select id from public.brands where name='Carolina Herrera'),  '212 Men',              'ch-212-men',             'Men',   'clean',   75, 6, 6, 82, 'Sommer',        'Alltag', ARRAY['Bergamotte','Grüne Noten','Gewürze'], ARRAY['Salbei','Ingwer'], ARRAY['Sandelholz','Moschus','Amber'])
on conflict (slug) do nothing;
