-- Auressa: Charge 15 – fehlende Gegenstuecke bekannter Marken (Damen/Herren/Unisex).
-- Faktenbasiert kuratiert nach oeffentlich dokumentierten Duftpyramiden.
-- Alle Marken existieren bereits. Im Supabase SQL Editor ausfuehren.
-- Wiederholbar: perfumes -> on conflict (slug) do nothing.
-- Hinweise:
--   price_chf  = ungefaehrer, oeffentlich bekannter Richtpreis (kann je Shop abweichen).
--   longevity/sillage/scentmatch_score = Auressa-Kuratierung, keine Nutzerbewertungen.
--   image_url / affiliate_url bleiben leer (NULL).

insert into public.perfumes
  (brand_id, perfume_name, slug, gender, fragrance_family, price_chf, longevity, sillage, scentmatch_score, season, occasion, top_notes, heart_notes, base_notes)
values
  -- ===== Prioritaet HOCH =====
  ((select id from public.brands where name='Dior'),                     'J''adore',                'dior-jadore',                 'Women',  'floral',   130, 7, 6, 90, 'Ganzjährig',    'Date',   ARRAY['Birne','Bergamotte','Melone'], ARRAY['Rose','Jasmin','Ylang-Ylang'], ARRAY['Moschus','Vanille','Zedernholz']),
  ((select id from public.brands where name='Dior'),                     'Sauvage',                 'dior-sauvage',                'Men',    'clean',    110, 8, 8, 90, 'Ganzjährig',    'Alltag', ARRAY['Bergamotte','Pfeffer'], ARRAY['Sichuan-Pfeffer','Lavendel','Geranie'], ARRAY['Ambroxan','Zedernholz','Labdanum']),
  ((select id from public.brands where name='Chanel'),                   'Bleu de Chanel',          'chanel-bleu-de-chanel',       'Men',    'woody',    135, 8, 7, 92, 'Ganzjährig',    'Abend',  ARRAY['Grapefruit','Zitrone','Pfefferminze'], ARRAY['Ingwer','Muskatnuss','Jasmin'], ARRAY['Sandelholz','Zedernholz','Weihrauch']),
  ((select id from public.brands where name='Chanel'),                   'N°5',                     'chanel-no-5',                 'Women',  'floral',   140, 7, 7, 90, 'Ganzjährig',    'Abend',  ARRAY['Aldehyde','Neroli','Ylang-Ylang'], ARRAY['Rose','Jasmin','Maiglöckchen'], ARRAY['Vetiver','Sandelholz','Vanille']),
  ((select id from public.brands where name='Yves Saint Laurent'),       'Black Opium',             'ysl-black-opium',             'Women',  'gourmand', 120, 8, 7, 90, 'Herbst/Winter', 'Date',   ARRAY['Rosa Pfeffer','Orangenblüte','Birne'], ARRAY['Kaffee','Jasmin'], ARRAY['Vanille','Patchouli','Zedernholz']),
  ((select id from public.brands where name='Yves Saint Laurent'),       'La Nuit de L''Homme',     'ysl-la-nuit-de-lhomme',       'Men',    'woody',    105, 7, 7, 89, 'Ganzjährig',    'Date',   ARRAY['Kardamom','Bergamotte'], ARRAY['Lavendel','Zedernholz'], ARRAY['Vetiver','Tonkabohne']),
  ((select id from public.brands where name='Carolina Herrera'),         'Good Girl',               'ch-good-girl',                'Women',  'gourmand', 110, 8, 8, 88, 'Herbst/Winter', 'Abend',  ARRAY['Mandel','Kaffee'], ARRAY['Tuberose','Jasmin'], ARRAY['Tonkabohne','Kakao','Vanille']),
  ((select id from public.brands where name='Valentino'),                'Born in Roma Uomo',       'valentino-born-in-roma-uomo', 'Men',    'woody',    100, 7, 7, 87, 'Ganzjährig',    'Alltag', ARRAY['Bergamotte','Wermut'], ARRAY['Salbei','Veilchenblatt'], ARRAY['Vetiver','Mineralholz']),

  -- ===== Prioritaet MITTEL =====
  ((select id from public.brands where name='Narciso Rodriguez'),        'For Him',                 'narciso-for-him',             'Men',    'woody',     85, 7, 6, 85, 'Ganzjährig',    'Date',   ARRAY['Muskat'], ARRAY['Veilchenblatt','Amberholz'], ARRAY['Moschus','Patchouli','Vetiver']),
  ((select id from public.brands where name='Dolce & Gabbana'),          'Light Blue',              'dolce-gabbana-light-blue',    'Women',  'clean',     75, 6, 5, 85, 'Sommer',        'Alltag', ARRAY['Zitrone','Apfel','Glockenblume'], ARRAY['Bambus','Jasmin','Weiße Rose'], ARRAY['Zedernholz','Amber','Moschus']),
  ((select id from public.brands where name='Creed'),                    'Aventus for Her',         'creed-aventus-for-her',       'Women',  'floral',   290, 7, 7, 90, 'Ganzjährig',    'Date',   ARRAY['Bergamotte','Grüner Apfel','Veilchenblatt'], ARRAY['Rose','Sambac-Jasmin'], ARRAY['Sandelholz','Moschus','Amber']),
  ((select id from public.brands where name='Viktor & Rolf'),            'Flowerbomb',              'viktor-rolf-flowerbomb',      'Women',  'floral',   130, 8, 7, 88, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte','Tee'], ARRAY['Jasmin','Orchidee','Rose','Freesie'], ARRAY['Patchouli','Vanille','Moschus']),
  ((select id from public.brands where name='Viktor & Rolf'),            'Spicebomb',               'viktor-rolf-spicebomb',       'Men',    'woody',    110, 7, 7, 87, 'Herbst/Winter', 'Abend',  ARRAY['Rosa Pfeffer','Bergamotte','Grapefruit'], ARRAY['Zimt','Safran','Paprika'], ARRAY['Tabak','Leder','Vetiver']),
  ((select id from public.brands where name='Mugler'),                   'A*Men',                   'mugler-amen',                 'Men',    'gourmand',  90, 8, 8, 86, 'Herbst/Winter', 'Abend',  ARRAY['Minze','Lavendel','Bergamotte'], ARRAY['Kaffee','Karamell','Patchouli'], ARRAY['Vanille','Tonkabohne','Schokolade']),
  ((select id from public.brands where name='Hugo Boss'),                'Boss Alive',              'boss-alive',                  'Women',  'floral',    80, 6, 6, 84, 'Ganzjährig',    'Alltag', ARRAY['Apfel','Blutorange'], ARRAY['Jasmin','Pfirsichblüte'], ARRAY['Vanille','Sandelholz']),
  ((select id from public.brands where name='Burberry'),                 'Hero',                    'burberry-hero',               'Men',    'woody',     95, 7, 7, 85, 'Ganzjährig',    'Alltag', ARRAY['Bergamotte'], ARRAY['Zedernholz','Tannennadeln'], ARRAY['Birkenholz','Benzoe']),
  ((select id from public.brands where name='Azzaro'),                   'Wanted Girl',             'azzaro-wanted-girl',          'Women',  'gourmand',  85, 7, 7, 84, 'Herbst/Winter', 'Date',   ARRAY['Ingwer','Rosa Pfeffer'], ARRAY['Datura-Blüte','Orangenblüte'], ARRAY['Vanille','Tonkabohne']),
  ((select id from public.brands where name='Davidoff'),                 'Cool Water Woman',        'davidoff-cool-water-woman',   'Women',  'clean',     50, 6, 5, 80, 'Sommer',        'Alltag', ARRAY['Ananas','Schwarze Johannisbeere','Quitte'], ARRAY['Seerose','Jasmin'], ARRAY['Weißer Moschus','Sandelholz']),
  ((select id from public.brands where name='Montblanc'),                'Signature',               'montblanc-signature',         'Women',  'floral',    60, 6, 5, 81, 'Frühling',      'Alltag', ARRAY['Bergamotte','Mandarine','Cassis'], ARRAY['Pfingstrose','Maiglöckchen','Jasmin'], ARRAY['Sandelholz','Moschus']),
  ((select id from public.brands where name='Versace'),                  'Eros Pour Femme',         'versace-eros-pour-femme',     'Women',  'floral',    85, 7, 7, 85, 'Ganzjährig',    'Date',   ARRAY['Zitrone','Granatapfel'], ARRAY['Sambac-Jasmin','Pfingstrose'], ARRAY['Sandelholz','Moschus','Amber']),
  ((select id from public.brands where name='Jean Paul Gaultier'),       'Scandal Pour Homme',      'jpg-scandal-pour-homme',      'Men',    'woody',     90, 7, 7, 84, 'Ganzjährig',    'Date',   ARRAY['Mandarine','Klee'], ARRAY['Tonkabohne','Salbei'], ARRAY['Vetiver','Karamell']),

  -- ===== Sternzeichen-Bonus (vervollstaendigt den Ratgeber-Artikel) =====
  ((select id from public.brands where name='Lattafa'),                  'Yara Tous',               'lattafa-yara-tous',           'Women',  'gourmand',  35, 8, 7, 83, 'Ganzjährig',    'Date',   ARRAY['Orchidee','Tropische Früchte'], ARRAY['Heliotrop','Jasmin'], ARRAY['Vanille','Moschus','Sandelholz']),
  ((select id from public.brands where name='Armaf'),                    'Club de Nuit Woman',      'armaf-club-de-nuit-woman',    'Women',  'floral',    35, 7, 7, 83, 'Ganzjährig',    'Date',   ARRAY['Ananas','Schwarze Johannisbeere','Bergamotte'], ARRAY['Pfirsich','Jasmin','Maiglöckchen'], ARRAY['Moschus','Amber','Vanille']),
  ((select id from public.brands where name='Lattafa'),                  'Mayar',                   'lattafa-mayar',               'Women',  'floral',    30, 7, 6, 82, 'Frühling',      'Alltag', ARRAY['Litschi','Mandarine','Birne'], ARRAY['Rose','Orangenblüte','Jasmin'], ARRAY['Moschus','Zedernholz','Vanille']),
  ((select id from public.brands where name='Armaf'),                    'Vanity Femme',            'armaf-vanity-femme',          'Women',  'floral',    30, 7, 6, 82, 'Frühling',      'Alltag', ARRAY['Bergamotte','Birne'], ARRAY['Rose','Jasmin','Maiglöckchen'], ARRAY['Moschus','Amber','Zedernholz']),

  -- ===== Prioritaet NIEDRIG (Nische / weitere) =====
  ((select id from public.brands where name='Amouage'),                  'Interlude Woman',         'amouage-interlude-woman',     'Women',  'floral',   320, 8, 8, 88, 'Herbst/Winter', 'Abend',  ARRAY['Rosa Pfeffer','Bergamotte','Koriander'], ARRAY['Rose','Orangenblüte','Weihrauch'], ARRAY['Amber','Moschus','Leder']),
  ((select id from public.brands where name='Parfums de Marly'),         'Valaya',                  'pdm-valaya',                  'Women',  'floral',   230, 7, 7, 87, 'Ganzjährig',    'Date',   ARRAY['Rosa Pfeffer','Bergamotte'], ARRAY['Orangenblüte','Weiße Blüten'], ARRAY['Vanille','Moschus','Amber']),
  ((select id from public.brands where name='Paco Rabanne'),             'Pure XS for Her',         'paco-pure-xs-for-her',        'Women',  'gourmand',  85, 7, 7, 84, 'Herbst/Winter', 'Date',   ARRAY['Ingwer','Schwarze Johannisbeere'], ARRAY['Vanille-Orchidee','Ylang-Ylang'], ARRAY['Sandelholz','Vanille','Moschus']),
  ((select id from public.brands where name='Maison Francis Kurkdjian'), 'Grand Soir',              'mfk-grand-soir',              'Unisex', 'gourmand', 250, 8, 7, 90, 'Herbst/Winter', 'Abend',  ARRAY['Bernstein','Benzoe'], ARRAY['Amber','Labdanum'], ARRAY['Vanille','Tonkabohne']),
  ((select id from public.brands where name='Bvlgari'),                  'Goldea',                  'bvlgari-goldea',              'Women',  'floral',    80, 6, 6, 82, 'Ganzjährig',    'Alltag', ARRAY['Moschus','Bergamotte'], ARRAY['Jasmin','Orangenblüte','Frangipani'], ARRAY['Amber','Patchouli','Papyrus']),
  ((select id from public.brands where name='Prada'),                    'Luna Rossa Ocean',        'prada-luna-rossa-ocean',      'Men',    'clean',     95, 7, 6, 85, 'Sommer',        'Alltag', ARRAY['Bergamotte','Mandarine'], ARRAY['Salbei','Lavendel'], ARRAY['Ambroxan','Patchouli','Zedernholz'])
on conflict (slug) do nothing;
