-- Auressa: Charge 19 – Notino-Bestseller (Lücken im Katalog), Durchgang 1.
-- Ziel: gängige, viel gesuchte Designer-Düfte ergänzen, damit der Katalog das
-- Notino-Sortiment besser abdeckt (für spätere Affiliate-Verlinkung).
-- Faktenbasiert nach öffentlich dokumentierten Duftpyramiden. Eigene Texte/Daten.
-- Alle Marken existieren bereits -> KEIN brands-Insert nötig.
-- Gegen Bestand (317 Düfte) geprüft: alle slugs/Namen sind neu.
-- Im Supabase SQL Editor ausführen. Wiederholbar: on conflict (slug) do nothing.

insert into public.perfumes
  (brand_id, perfume_name, slug, gender, fragrance_family, price_chf, longevity, sillage, scentmatch_score, season, occasion, top_notes, heart_notes, base_notes)
values
  ((select id from public.brands where name='Dior'),               'J''adore',                  'dior-jadore',                  'Women',  'floral',   135, 7, 6, 88, 'Ganzjährig',    'Date',   ARRAY['Birne','Bergamotte','Melone'], ARRAY['Rose','Jasmin','Ylang-Ylang'], ARRAY['Moschus','Zedernholz','Vanille']),
  ((select id from public.brands where name='Dior'),               'Miss Dior Blooming Bouquet','dior-miss-dior-blooming',      'Women',  'floral',   115, 6, 5, 85, 'Frühling',      'Alltag', ARRAY['Sizilianische Mandarine'], ARRAY['Pfingstrose','Rose','Aprikose'], ARRAY['Weißer Moschus']),
  ((select id from public.brands where name='Dior'),               'Dior Addict',               'dior-addict',                  'Women',  'floral',   125, 8, 7, 85, 'Herbst/Winter', 'Abend',  ARRAY['Mandarine','Bergamotte'], ARRAY['Jasmin Sambac','Orangenblüte'], ARRAY['Vanille','Tonkabohne','Sandelholz']),
  ((select id from public.brands where name='Chanel'),             'Chance',                    'chanel-chance',                'Women',  'floral',   130, 7, 6, 86, 'Ganzjährig',    'Date',   ARRAY['Pink Pfeffer','Zitrone'], ARRAY['Jasmin','Iris'], ARRAY['Patchouli','Vetiver','Weißer Moschus']),
  ((select id from public.brands where name='Yves Saint Laurent'), 'La Nuit de L''Homme',       'ysl-la-nuit-de-lhomme',        'Men',    'woody',    105, 7, 7, 89, 'Herbst/Winter', 'Date',   ARRAY['Kardamom','Bergamotte'], ARRAY['Lavendel','Zedernholz'], ARRAY['Tonkabohne','Vetiver']),
  ((select id from public.brands where name='Yves Saint Laurent'), 'Y Eau de Toilette',         'ysl-y-edt',                    'Men',    'clean',    90,  6, 6, 85, 'Frühling',      'Büro',   ARRAY['Bergamotte','Ingwer','Salbei'], ARRAY['Salbei','Geranie','Apfel'], ARRAY['Amberholz','Zedernholz','Vetiver']),
  ((select id from public.brands where name='Giorgio Armani'),     'Acqua di Giò pour Homme',   'armani-acqua-di-gio-homme',    'Men',    'clean',    95,  6, 6, 88, 'Sommer',        'Alltag', ARRAY['Bergamotte','Neroli','Limette'], ARRAY['Jasmin','Meeresnoten','Rosmarin'], ARRAY['Patchouli','Zedernholz','Moschus']),
  ((select id from public.brands where name='Giorgio Armani'),     'Acqua di Giò Profondo',     'armani-acqua-di-gio-profondo', 'Men',    'clean',    105, 7, 6, 86, 'Sommer',        'Date',   ARRAY['Meeresnoten','Bergamotte','Aquozon'], ARRAY['Rosmarin','Lavendel','Zypresse'], ARRAY['Mineralnoten','Patchouli','Moschus']),
  ((select id from public.brands where name='Lancome'),            'La Vie Est Belle',          'lancome-la-vie-est-belle',     'Women',  'gourmand', 120, 8, 7, 89, 'Herbst/Winter', 'Date',   ARRAY['Schwarze Johannisbeere','Birne'], ARRAY['Iris','Jasmin','Orangenblüte'], ARRAY['Praline','Vanille','Tonkabohne','Patchouli']),
  ((select id from public.brands where name='Lancome'),            'Trésor',                    'lancome-tresor',               'Women',  'floral',   100, 7, 6, 84, 'Herbst/Winter', 'Date',   ARRAY['Aprikose','Litschi','Rose'], ARRAY['Iris','Heliotrop','Jasmin'], ARRAY['Sandelholz','Vanille','Moschus']),
  ((select id from public.brands where name='Givenchy'),           'Gentleman',                 'givenchy-gentleman-edp',       'Men',    'woody',    100, 8, 7, 86, 'Herbst/Winter', 'Abend',  ARRAY['Birne','Iris'], ARRAY['Iris','Lavendel'], ARRAY['Patchouli','Leder','Vanille']),
  ((select id from public.brands where name='Givenchy'),           'L''Interdit',               'givenchy-linterdit',           'Women',  'floral',   115, 7, 7, 86, 'Ganzjährig',    'Date',   ARRAY['Birne','Bergamotte'], ARRAY['Tuberose','Orangenblüte','Jasmin'], ARRAY['Vetiver','Patchouli','Ambroxan']),
  ((select id from public.brands where name='Carolina Herrera'),   'CH',                        'carolina-herrera-ch',          'Women',  'woody',    90,  7, 6, 84, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte','Grapefruit','Orange'], ARRAY['Jasmin','Rose','Maiglöckchen'], ARRAY['Leder','Amber','Praline','Sandelholz']),
  ((select id from public.brands where name='Carolina Herrera'),   '212 Sexy',                  'carolina-herrera-212-sexy',    'Women',  'floral',   85,  6, 6, 82, 'Ganzjährig',    'Date',   ARRAY['Bergamotte','Mandarine','Pink Pfeffer'], ARRAY['Rose','Pfingstrose','Gardenie'], ARRAY['Vanille','Sandelholz','Moschus']),
  ((select id from public.brands where name='Valentino'),          'Uomo',                      'valentino-uomo',               'Men',    'gourmand', 95,  7, 7, 85, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte','Myrte'], ARRAY['Kaffee','Haselnusscreme'], ARRAY['Leder','Zedernholz']),
  ((select id from public.brands where name='Valentino'),          'Voce Viva',                 'valentino-voce-viva',          'Women',  'floral',   110, 7, 6, 84, 'Frühling',      'Date',   ARRAY['Bergamotte','Mandarine'], ARRAY['Orangenblüte','Gardenie','Ingwerblüte'], ARRAY['Vanille','Kristallmoschus']),
  ((select id from public.brands where name='Prada'),              'Luna Rossa Black',          'prada-luna-rossa-black',       'Men',    'woody',    115, 8, 7, 86, 'Herbst/Winter', 'Abend',  ARRAY['Bergamotte','Engelwurz'], ARRAY['Lavendel','Iris'], ARRAY['Patchouli','Amber','Moschus']),
  ((select id from public.brands where name='Paco Rabanne'),       'Black XS',                  'paco-rabanne-black-xs',        'Men',    'woody',    70,  7, 6, 83, 'Herbst/Winter', 'Date',   ARRAY['Praline','Zitrone','Kalmus'], ARRAY['Zimt','Salbei','Lavendel'], ARRAY['Patchouli','Tonkabohne','Amber']),
  ((select id from public.brands where name='Paco Rabanne'),       '1 Million Lucky',           'paco-rabanne-1-million-lucky', 'Men',    'woody',    80,  7, 7, 84, 'Herbst/Winter', 'Date',   ARRAY['Pflaume','Haselnuss'], ARRAY['Honig','Damaszener Rose'], ARRAY['Zedernholz','Amberholz']),
  ((select id from public.brands where name='Calvin Klein'),       'CK One',                    'ck-one',                       'Unisex', 'clean',    45,  5, 5, 83, 'Sommer',        'Alltag', ARRAY['Bergamotte','Kardamom','Ananas','Zitrone'], ARRAY['Jasmin','Maiglöckchen','Muskatnuss','Veilchen'], ARRAY['Moschus','Amber','Zedernholz']),
  ((select id from public.brands where name='Calvin Klein'),       'Eternity for Men',          'ck-eternity-for-men',          'Men',    'woody',    55,  6, 6, 82, 'Frühling',      'Büro',   ARRAY['Lavendel','Mandarine','Zitrone'], ARRAY['Salbei','Geranie','Maiglöckchen'], ARRAY['Sandelholz','Amber','Moschus']),
  ((select id from public.brands where name='Mugler'),             'Alien Goddess',             'mugler-alien-goddess',         'Women',  'floral',   100, 7, 7, 85, 'Frühling',      'Date',   ARRAY['Bergamotte'], ARRAY['Jasmin Sambac','Orangenblüte'], ARRAY['Bourbon-Vanille','Cashmeran']),
  ((select id from public.brands where name='Viktor & Rolf'),      'Spicebomb Extreme',         'viktor-rolf-spicebomb-extreme','Men',    'gourmand', 105, 8, 8, 87, 'Herbst/Winter', 'Abend',  ARRAY['Schwarzer Pfeffer','Lavendel'], ARRAY['Zimt','Tabak','Kreuzkümmel'], ARRAY['Vanille','Tonkabohne']),
  ((select id from public.brands where name='Versace'),            'Dylan Blue Pour Femme',     'versace-dylan-blue-femme',     'Women',  'floral',   75,  7, 6, 83, 'Frühling',      'Date',   ARRAY['Schwarze Johannisbeere','Apfel','Birne'], ARRAY['Rose','Pflaume','Pfingstrose'], ARRAY['Moschus','Sandelholz','Amber']),
  ((select id from public.brands where name='Hugo Boss'),          'Boss Bottled Infinite',     'boss-bottled-infinite',        'Men',    'woody',    80,  7, 6, 83, 'Frühling',      'Büro',   ARRAY['Apfel','Mandarine'], ARRAY['Lavendel','Geranie','Zimt'], ARRAY['Sandelholz','Patchouli']),
  ((select id from public.brands where name='Hugo Boss'),          'Hugo Man',                  'hugo-man',                     'Men',    'clean',    50,  6, 5, 81, 'Sommer',        'Alltag', ARRAY['Grüner Apfel','Grapefruit','Basilikum'], ARRAY['Tanne','Salbei','Gewürznelke'], ARRAY['Zedernholz','Patchouli','Moschus']),
  ((select id from public.brands where name='Montblanc'),          'Legend Spirit',             'montblanc-legend-spirit',      'Men',    'clean',    65,  6, 6, 83, 'Sommer',        'Büro',   ARRAY['Grapefruit','Bergamotte','Zitrone'], ARRAY['Lavendel','Wassernoten','Pink Pfeffer'], ARRAY['Zedernholz','Moschus']),
  ((select id from public.brands where name='Azzaro'),             'Azzaro pour Homme',         'azzaro-pour-homme',            'Men',    'woody',    60,  7, 6, 84, 'Herbst/Winter', 'Abend',  ARRAY['Lavendel','Anis','Bergamotte','Basilikum'], ARRAY['Geranie','Vetiver','Patchouli'], ARRAY['Eichenmoos','Leder','Moschus']),
  ((select id from public.brands where name='Davidoff'),           'Cool Water Intense',        'davidoff-cool-water-intense',  'Men',    'woody',    55,  7, 6, 81, 'Herbst/Winter', 'Alltag', ARRAY['Grapefruit','Bergamotte'], ARRAY['Lavendel','Salbei','Geranie'], ARRAY['Zedernholz','Patchouli','Amber']),
  ((select id from public.brands where name='Tom Ford'),           'Grey Vetiver',              'tf-grey-vetiver',              'Men',    'woody',    180, 7, 6, 86, 'Ganzjährig',    'Büro',   ARRAY['Grapefruit','Orangenblüte','Muskatnuss'], ARRAY['Vetiver','Salbei','Iris'], ARRAY['Amber','Holznoten','Eichenmoos']),
  ((select id from public.brands where name='Tom Ford'),           'Neroli Portofino',          'tf-neroli-portofino',          'Unisex', 'clean',    230, 5, 6, 85, 'Sommer',        'Alltag', ARRAY['Bergamotte','Mandarine','Zitrone','Neroli'], ARRAY['Orangenblüte','Jasmin','Lavendel'], ARRAY['Amber','Moschus','Ambrette']),
  ((select id from public.brands where name='Creed'),              'Viking',                    'creed-viking',                 'Men',    'woody',    320, 7, 7, 86, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte','Pfeffer','Zitrone'], ARRAY['Lavendel','Rose','Wacholder'], ARRAY['Sandelholz','Vetiver','Patchouli']),
  ((select id from public.brands where name='Gucci'),              'Guilty Absolute Pour Homme','gucci-guilty-absolute',        'Men',    'woody',    100, 8, 7, 85, 'Herbst/Winter', 'Abend',  ARRAY['Leder','Pink Pfeffer'], ARRAY['Vetiver','Patchouli'], ARRAY['Holznoten','Zedernholz','Eichenmoos']),
  ((select id from public.brands where name='Gucci'),              'Flora Gorgeous Jasmine',    'gucci-flora-gorgeous-jasmine', 'Women',  'floral',   115, 6, 6, 83, 'Frühling',      'Date',   ARRAY['Mandarine','Birne'], ARRAY['Jasmin','Magnolie'], ARRAY['Sandelholz','Moschus']),
  ((select id from public.brands where name='Lattafa'),            'Raghba',                    'lattafa-raghba',               'Unisex', 'gourmand', 30,  8, 7, 84, 'Herbst/Winter', 'Abend',  ARRAY['Vanille'], ARRAY['Oud','Weihrauch'], ARRAY['Brauner Zucker','Amber','Moschus']),
  ((select id from public.brands where name='Armaf'),              'Club de Nuit Untold',       'armaf-cdn-untold',             'Unisex', 'woody',    45,  8, 8, 85, 'Ganzjährig',    'Abend',  ARRAY['Bergamotte','Safran','Jasmin'], ARRAY['Amberholz','Zedernholz'], ARRAY['Vanille','Eichenmoos','Moschus'])
on conflict (slug) do nothing;
