-- Auressa: Charge 20 – Notino-Bestseller (Lücken im Katalog), Durchgang 2.
-- Weitere gängige Designer-Düfte + bekannte Klone, die noch fehlten.
-- Faktenbasiert nach öffentlich dokumentierten Duftpyramiden. Eigene Texte/Daten.
-- Alle Marken existieren bereits -> KEIN brands-Insert nötig.
-- Gegen Bestand inkl. Charge 19 geprüft: alle slugs/Namen sind neu.
-- Im Supabase SQL Editor ausführen. Wiederholbar: on conflict (slug) do nothing.

insert into public.perfumes
  (brand_id, perfume_name, slug, gender, fragrance_family, price_chf, longevity, sillage, scentmatch_score, season, occasion, top_notes, heart_notes, base_notes)
values
  ((select id from public.brands where name='Dior'),               'Sauvage Eau de Parfum',          'dior-sauvage-edp',            'Men',    'woody',    125, 8, 8, 89, 'Ganzjährig',    'Date',   ARRAY['Bergamotte','Mandarine'], ARRAY['Sichuan-Pfeffer','Lavendel','Sternanis'], ARRAY['Ambroxan','Vanille','Zedernholz']),
  ((select id from public.brands where name='Dior'),               'Eau Sauvage',                    'dior-eau-sauvage',            'Men',    'clean',    95,  6, 5, 84, 'Sommer',        'Büro',   ARRAY['Zitrone','Bergamotte','Basilikum'], ARRAY['Jasmin','Rosmarin','Koriander'], ARRAY['Vetiver','Eichenmoos','Moschus']),
  ((select id from public.brands where name='Dior'),               'Pure Poison',                    'dior-pure-poison',            'Women',  'floral',   115, 7, 7, 84, 'Frühling',      'Date',   ARRAY['Bergamotte','Orange'], ARRAY['Gardenie','Jasmin','Orangenblüte'], ARRAY['Sandelholz','Amber','Moschus']),
  ((select id from public.brands where name='Chanel'),             'Coco',                           'chanel-coco',                 'Women',  'floral',   135, 8, 7, 85, 'Herbst/Winter', 'Abend',  ARRAY['Mandarine','Pfirsich','Koriander'], ARRAY['Rose','Gewürznelke','Mimose'], ARRAY['Amber','Tonkabohne','Vanille']),
  ((select id from public.brands where name='Chanel'),             'Allure Homme',                   'chanel-allure-homme',         'Men',    'woody',    115, 7, 6, 85, 'Ganzjährig',    'Büro',   ARRAY['Mandarine','Bergamotte','Zitrone'], ARRAY['Pfeffer','Zedernholz','Tonkabohne'], ARRAY['Vanille','Vetiver','Patchouli']),
  ((select id from public.brands where name='Chanel'),             'N°5 L''Eau',                     'chanel-n5-leau',              'Women',  'floral',   130, 6, 5, 85, 'Frühling',      'Alltag', ARRAY['Zitrone','Mandarine','Aldehyde'], ARRAY['Rose','Jasmin','Ylang-Ylang'], ARRAY['Zedernholz','Weißer Moschus']),
  ((select id from public.brands where name='Yves Saint Laurent'), 'Opium',                          'ysl-opium',                   'Women',  'gourmand', 100, 8, 8, 84, 'Herbst/Winter', 'Abend',  ARRAY['Mandarine','Pflaume','Gewürznelke'], ARRAY['Myrrhe','Rose','Zimt'], ARRAY['Amber','Patchouli','Vanille']),
  ((select id from public.brands where name='Yves Saint Laurent'), 'Libre Intense',                  'ysl-libre-intense',           'Women',  'floral',   120, 8, 7, 86, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte','Mandarine'], ARRAY['Lavendel','Orangenblüte','Jasmin'], ARRAY['Vanille','Tonkabohne','Amber']),
  ((select id from public.brands where name='Emporio Armani'),     'Stronger With You Intensely',    'emporio-swy-intensely',       'Men',    'gourmand', 90,  8, 8, 86, 'Herbst/Winter', 'Abend',  ARRAY['Pink Pfeffer','Zimt','Lavendel'], ARRAY['Salbei','Tonkabohne'], ARRAY['Vanille','Amber','Tabak']),
  ((select id from public.brands where name='Versace'),            'Yellow Diamond',                 'versace-yellow-diamond',      'Women',  'floral',   70,  6, 6, 82, 'Sommer',        'Alltag', ARRAY['Bergamotte','Birne','Neroli'], ARRAY['Orangenblüte','Mimose','Freesie'], ARRAY['Amber','Moschus','Guajakholz']),
  ((select id from public.brands where name='Versace'),            'The Dreamer',                    'versace-dreamer',             'Men',    'woody',    60,  6, 6, 81, 'Herbst/Winter', 'Abend',  ARRAY['Lavendel','Tabakblüte'], ARRAY['Iris','Wermut'], ARRAY['Tabak','Amber','Holznoten']),
  ((select id from public.brands where name='Paco Rabanne'),       'Invictus Victory',               'pr-invictus-victory',         'Men',    'woody',    95,  8, 8, 85, 'Herbst/Winter', 'Abend',  ARRAY['Bergamotte','Schwarzer Pfeffer'], ARRAY['Weihrauch','Zimt'], ARRAY['Amberholz','Patchouli','Guajakholz']),
  ((select id from public.brands where name='Paco Rabanne'),       'Lady Million Empire',            'pr-lady-million-empire',      'Women',  'floral',   85,  7, 7, 83, 'Ganzjährig',    'Date',   ARRAY['Bergamotte','Grüner Apfel'], ARRAY['Jasmin','Orangenblüte'], ARRAY['Vanille','Sandelholz','Moschus']),
  ((select id from public.brands where name='Gucci'),              'Bamboo',                         'gucci-bamboo',                'Women',  'floral',   90,  7, 6, 83, 'Frühling',      'Date',   ARRAY['Bergamotte'], ARRAY['Casablanca-Lilie','Orangenblüte','Ylang-Ylang'], ARRAY['Sandelholz','Vanille','Amber']),
  ((select id from public.brands where name='Gucci'),              'Rush',                           'gucci-rush',                  'Women',  'floral',   75,  7, 7, 83, 'Herbst/Winter', 'Date',   ARRAY['Freesie','Koriander','Pfirsich'], ARRAY['Gardenie','Jasmin','Rose'], ARRAY['Patchouli','Vanille','Vetiver']),
  ((select id from public.brands where name='Givenchy'),           'Ange ou Démon Le Secret',        'givenchy-ange-ou-demon-secret','Women', 'floral',   85,  7, 6, 83, 'Frühling',      'Date',   ARRAY['Zitrone','Grüner Tee'], ARRAY['Jasmin','Pflaumenblüte'], ARRAY['Patchouli','Tonkabohne','Sandelholz']),
  ((select id from public.brands where name='Dolce & Gabbana'),    'The Only One',                   'dg-the-only-one',             'Women',  'gourmand', 95,  7, 7, 84, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte','Veilchen'], ARRAY['Kaffee','Orangenblüte'], ARRAY['Vanille','Iris','Patchouli']),
  ((select id from public.brands where name='Dolce & Gabbana'),    'L''Imperatrice',                 'dg-limperatrice',             'Women',  'clean',    70,  5, 5, 82, 'Sommer',        'Alltag', ARRAY['Kiwi','Wassermelone'], ARRAY['Cyclamen','Jasmin'], ARRAY['Moschus','Amber']),
  ((select id from public.brands where name='Dolce & Gabbana'),    'The One Gold for Men',           'dg-the-one-gold-men',         'Men',    'gourmand', 95,  8, 7, 85, 'Herbst/Winter', 'Abend',  ARRAY['Bergamotte','Grapefruit','Pfeffer'], ARRAY['Salbei','Tabak'], ARRAY['Amber','Vanille','Patchouli']),
  ((select id from public.brands where name='Jean Paul Gaultier'), 'Le Male Elixir',                 'jpg-le-male-elixir',          'Men',    'gourmand', 110, 9, 8, 87, 'Herbst/Winter', 'Abend',  ARRAY['Minze','Lavendel'], ARRAY['Vanille','Honig'], ARRAY['Benzoe','Tonkabohne','Holznoten']),
  ((select id from public.brands where name='Jean Paul Gaultier'), 'Classique',                      'jpg-classique',               'Women',  'floral',   90,  7, 7, 84, 'Herbst/Winter', 'Date',   ARRAY['Rose','Orangenblüte','Anis'], ARRAY['Ingwer','Ylang-Ylang','Pflaume'], ARRAY['Vanille','Amber','Sandelholz']),
  ((select id from public.brands where name='Hugo Boss'),          'Boss The Scent for Her',         'boss-the-scent-her',          'Women',  'gourmand', 70,  6, 6, 82, 'Herbst/Winter', 'Date',   ARRAY['Osmanthus','Honig'], ARRAY['Pfirsich','Freesie'], ARRAY['Kakao','Moschus']),
  ((select id from public.brands where name='Lancome'),            'Hypnôse',                        'lancome-hypnose',             'Women',  'floral',   85,  7, 7, 83, 'Herbst/Winter', 'Date',   ARRAY['Passionsblume'], ARRAY['Jasmin','Pfingstrose'], ARRAY['Vanille','Vetiver','Sandelholz']),
  ((select id from public.brands where name='Lancome'),            'Miracle',                        'lancome-miracle',             'Women',  'floral',   80,  6, 6, 82, 'Frühling',      'Date',   ARRAY['Litschi','Freesie','Pfeffer'], ARRAY['Magnolie','Jasmin','Ingwer'], ARRAY['Moschus','Jasminholz','Amber']),
  ((select id from public.brands where name='Carolina Herrera'),   '212 VIP Black',                  'ch-212-vip-black',            'Men',    'gourmand', 85,  8, 8, 85, 'Herbst/Winter', 'Abend',  ARRAY['Anis','Lavendel'], ARRAY['Schwarze Vanille','Pfeffer'], ARRAY['Leder','Holznoten','Moschus']),
  ((select id from public.brands where name='Carolina Herrera'),   'CH Men',                         'carolina-herrera-ch-men',     'Men',    'woody',    80,  7, 6, 83, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte','Grapefruit','Zitrone'], ARRAY['Jasmin','Salbei','Muskatnuss'], ARRAY['Leder','Zedernholz','Tonkabohne']),
  ((select id from public.brands where name='Prada'),              'La Femme',                       'prada-la-femme',              'Women',  'floral',   100, 7, 6, 84, 'Herbst/Winter', 'Date',   ARRAY['Frangipani'], ARRAY['Ylang-Ylang','Tuberose'], ARRAY['Vanille','Iris','Bienenwachs']),
  ((select id from public.brands where name='Valentino'),          'Donna',                          'valentino-donna',             'Women',  'floral',   105, 7, 7, 84, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte'], ARRAY['Rose','Iris'], ARRAY['Leder','Patchouli','Vanille']),
  ((select id from public.brands where name='Tom Ford'),           'Tobacco Oud',                    'tf-tobacco-oud',              'Unisex', 'woody',    250, 9, 8, 87, 'Herbst/Winter', 'Abend',  ARRAY['Gewürze','Koriander'], ARRAY['Oud','Sandelholz','Zedernholz'], ARRAY['Tabak','Vanille','Amber']),
  ((select id from public.brands where name='Tom Ford'),           'Velvet Orchid',                  'tf-velvet-orchid',            'Women',  'floral',   180, 8, 7, 86, 'Herbst/Winter', 'Date',   ARRAY['Bergamotte','Rum','Honig'], ARRAY['Orchidee','Jasmin','Rose'], ARRAY['Vanille','Sandelholz','Amber']),
  ((select id from public.brands where name='Tom Ford'),           'Costa Azzurra',                  'tf-costa-azzurra',            'Unisex', 'woody',    230, 7, 6, 85, 'Sommer',        'Alltag', ARRAY['Seetang','Zitrusfrüchte'], ARRAY['Lavendel','Wacholder','Driftwood'], ARRAY['Eichenmoos','Vetiver','Amber']),
  ((select id from public.brands where name='Creed'),              'Royal Oud',                      'creed-royal-oud',             'Unisex', 'woody',    320, 8, 7, 87, 'Ganzjährig',    'Abend',  ARRAY['Zitrone','Bergamotte','Rosa Pfeffer'], ARRAY['Zedernholz','Galbanum','Angelika'], ARRAY['Oud','Sandelholz','Moschus']),
  ((select id from public.brands where name='Creed'),              'Millésime Imperial',             'creed-millesime-imperial',    'Unisex', 'clean',    340, 7, 6, 86, 'Sommer',        'Date',   ARRAY['Bergamotte','Zitrone','Meeresnoten'], ARRAY['Iris','Veilchen'], ARRAY['Sandelholz','Moschus','Amber']),
  ((select id from public.brands where name='Lattafa'),            'Khamrah Qahwa',                  'lattafa-khamrah-qahwa',       'Unisex', 'gourmand', 35,  8, 7, 84, 'Herbst/Winter', 'Abend',  ARRAY['Kaffee','Zimt','Muskatnuss'], ARRAY['Dattel','Praline'], ARRAY['Vanille','Tonkabohne','Benzoe']),
  ((select id from public.brands where name='Lattafa'),            'Maahir',                         'lattafa-maahir',              'Men',    'woody',    30,  7, 6, 82, 'Ganzjährig',    'Date',   ARRAY['Apfel','Zitrone','Safran'], ARRAY['Rose','Bergamotte'], ARRAY['Amber','Moschus','Zedernholz']),
  ((select id from public.brands where name='Armaf'),              'Club de Nuit Milestone',         'armaf-cdn-milestone',         'Unisex', 'woody',    45,  8, 8, 85, 'Ganzjährig',    'Abend',  ARRAY['Bergamotte','Grüne Noten','Ananas'], ARRAY['Pfingstrose','Pflaume','Jasmin'], ARRAY['Amber','Moschus','Vanille'])
on conflict (slug) do nothing;
