// Gift Finder: Duftrichtungen mit ihren charakteristischen Noten
// Editierbar ohne Code-Änderungen – einfach Noten hinzufügen/entfernen

export type GiftStyle = {
  id: 'fresh' | 'elegant' | 'warm' | 'bold';
  label: string;
  description: string;
  notes: string[];
  familyBonus?: string[];
};

export const GIFT_FINDER_STYLES: GiftStyle[] = [
  {
    id: 'fresh',
    label: 'Frisch und sportlich',
    description: 'Belebend, unbeschwert, nach frischer Luft – ideal für aktive, moderne Menschen.',
    notes: [
      'Zitrone',
      'Grapefruit',
      'Mandarine',
      'Orange',
      'Limette',
      'Yuzu',
      'Neroli',
      'Petitgrain',
      'Bitterorange',
      'Blutorange',
      'Grüne Mandarine',
      'Minze',
      'Meeresnoten',
      'Mineralnoten',
      'Ingwer',
      'Grüner Apfel',
      'Grüner Tee',
      'Grüne Noten',
      'Rosmarin',
      'Basilikum',
      'Wacholder',
      'Zypresse',
    ],
    familyBonus: ['clean'],
  },
  {
    id: 'elegant',
    label: 'Elegant und klassisch',
    description: 'Zeitlos, gepflegt, fein – für anspruchsvolle, elegante Personen.',
    notes: [
      'Iris',
      'Veilchen',
      'Veilchenblatt',
      'Rose',
      'Türkische Rose',
      'Lavendel',
      'Vetiver',
      'Leder',
      'Aldehyde',
      'Maiglöckchen',
      'Magnolie',
      'Pfingstrose',
      'Geranie',
      'Salbei',
      'Eichenmoos',
      'Ambrette',
      'Papyrus',
    ],
    familyBonus: ['floral', 'woody'],
  },
  {
    id: 'warm',
    label: 'Warm und gemütlich',
    description: 'Kuschelig, süss, einladend – für gemütliche, genussvolle Menschen.',
    notes: [
      'Vanille',
      'Tonkabohne',
      'Karamell',
      'Praline',
      'Honig',
      'Kakao',
      'Schokolade',
      'Mandel',
      'Bittermandel',
      'Kastanie',
      'Marshmallow',
      'Brauner Zucker',
      'Zimt',
      'Kardamom',
      'Muskatnuss',
      'Muskat',
      'Benzoe',
      'Kaffee',
      'Kokosnuss',
      'Mandelmilch',
      'Bourbon-Vanille',
      'Schwarze Vanille',
      'Vanilleorchidee',
      'Heliotrop',
    ],
    familyBonus: ['gourmand'],
  },
  {
    id: 'bold',
    label: 'Auffällig und sinnlich',
    description: 'Intensiv, verführerisch, unvergesslich – für charismatische, mut­ige Menschen.',
    notes: [
      'Oud',
      'Tabak',
      'Tabakblatt',
      'Tuberose',
      'Ylang-Ylang',
      'Gardenie',
      'Frangipani',
      'Orchidee',
      'Weihrauch',
      'Myrrhe',
      'Labdanum',
      'Safran',
      'Rum',
      'Bourbon',
      'Pflaume',
      'Kirsche',
    ],
  },
];
